language: en-US
early_access: false
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  tools:
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    shellcheck:
      enabled: true
chat:
  auto_reply: true
tone_instructions: "Focus on Go idioms, API design, security (SQL injection, auth), performance, GORM usage, and testing. Flag security issues immediately with code examples."
