version: '3'

tasks:
  run:
    desc: Run the admin API locally
    cmds:
      - go run cmd/api/main.go

  build:
    desc: Build the admin API binary
    cmds:
      - go build -o bin/admin-api cmd/api/main.go

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  swagger:
    desc: Generate Swagger documentation
    cmds:
      - swag init -g cmd/api/main.go -o docs

  clean:
    desc: Clean build artifacts and docs
    cmds:
      - rm -rf bin/ docs/

  docker-build:
    desc: Build Docker image
    cmds:
      - docker build -t admin-api .

  docker-run:
    desc: Run service with docker-compose
    cmds:
      - docker-compose up -d

  docker-stop:
    desc: Stop docker-compose services
    cmds:
      - docker-compose down

  docker-logs:
    desc: View admin API logs
    cmds:
      - docker-compose logs -f admin-api
